Install from media

diff --git a/instlr b/instlr
--- a/instlr
+++ b/instlr
@@ -43,36 +43,78 @@ fi
 
 PREFIX=$1
 
-cd $PREFIX
-$WGET $PKGHOST/file-base.tar.bz2 -O$PREFIX/file-base.tar.bz2
-$TAR xf file-base.tar.bz2
-$RM file-base.tar.bz2
-
-if [ `$UNAME -m` == "x86_64" ]; then
-	$LN -s lib lib64
-	cd usr
-	$LN -s lib lib64
+if [ ! -d "$PREFIX" ]; then
+	echo "Error: Please provide a valid directory";
+	exit 1;
 fi
 
+echo "Get packages from the internet, or use booted media? (internet/media): "; read internetormedia;
 
-$CURL -L -s https://github.com/nemasu/noop-linux/raw/master/pkgr > $PREFIX/usr/sbin/pkgr
-
-$CHMOD a+x $PREFIX/usr/sbin/pkgr
-export PATH=$PREFIX/usr/sbin:$PATH
-
-PREFIX=$PREFIX pkgr -s
-export PKGR_SUPPRESS_P_OUTPUT=1
-
-if [ "`$UNAME -m`" != "armv6l" ];
+if [ "$internetormedia" == "internet" ];
 then
-	EXTRA="grub cryptsetup"
+
+
+	cd $PREFIX
+	$WGET $PKGHOST/file-base.tar.bz2 -O$PREFIX/file-base.tar.bz2
+	$TAR xf file-base.tar.bz2
+	$RM file-base.tar.bz2
+
+	if [ `$UNAME -m` == "x86_64" ]; then
+		$LN -s lib lib64
+		cd usr
+		$LN -s lib lib64
+	fi
+
+
+	$CURL -L -s https://github.com/nemasu/noop-linux/raw/master/pkgr > $PREFIX/usr/sbin/pkgr
+
+	$CHMOD a+x $PREFIX/usr/sbin/pkgr
+	export PATH=$PREFIX/usr/sbin:$PATH
+
+	PREFIX=$PREFIX pkgr -s
+	export PKGR_SUPPRESS_P_OUTPUT=1
+
+	if [ "`$UNAME -m`" != "armv6l" ];
+	then
+		EXTRA="grub cryptsetup"
+	fi
+
+	for i in glibc trunc which busybox bc tzdata systemd shadow coreutils bash wget grep sed perl findutils curl gawk procps tar bzip2 gzip dhcpcd inetutils iproute2 wpa_supplicant wireless_tools kbd vim ca-certificates openresolv networkmanager linux-kernel linux-firmware $EXTRA;
+	do
+		PREFIX=$PREFIX pkgr -i $i
+	done
+else
+
+	if [ ! -d /var/noop/installed ]; then
+		echo "Error: Not booted from valid noop Linux media, use internet instalation method.";
+		exit 1;
+	fi
+
+	for i in `ls /var/noop/installed`
+	do
+		echo "Copying package $i"
+		for j in `sed -n -e '/FILES:/,$p' /var/noop/installed/$i | sed '/FILES:/d'`
+		do  
+			cp --parents "$j" "$1/" &> /dev/null
+		done
+	done
+
+	echo -n "Copying metadata...";
+	cp -r /var/noop $PREFIX/var/
+	echo "done.";
+
+	echo -n "Resetting base file system...";
+	pushd $PREFIX &> /dev/null
+	wget nooplinux.org/noop/packages/x86_64/file-base.tar.bz2
+	tar xf file-base.tar.bz2 && rm file-base.tar.bz2
+	popd &> /dev/null
+	$CURL -L -s https://github.com/nemasu/noop-linux/raw/master/pkgr > $PREFIX/usr/sbin/pkgr
+	$CHMOD a+x $PREFIX/usr/sbin/pkgr
+	export PATH=$PREFIX/usr/sbin:$PATH
+	PREFIX=$PREFIX pkgr -s
+	echo "done.";
+
 fi
-
-for i in glibc trunc which busybox bc tzdata systemd shadow coreutils bash wget grep sed perl findutils curl gawk procps tar bzip2 gzip dhcpcd inetutils iproute2 wpa_supplicant wireless_tools kbd vim ca-certificates openresolv networkmanager linux-kernel linux-firmware $EXTRA;
-do
-	PREFIX=$PREFIX pkgr -i $i
-done
-
 $MOUNT --bind /dev $PREFIX/dev
 $MOUNT --bind /proc $PREFIX/proc
 $MOUNT --bind /sys $PREFIX/sys
