pkgr -V improvements

diff --git a/pkgr b/pkgr
--- a/pkgr
+++ b/pkgr
@@ -79,10 +79,10 @@ if [ -z $1 ] || [ $1 == "-h" ] || [ $1 == "--help" ]; then
 	$echo -e "\t-r,\t--remove pkg                  Remove"
 	$echo -e "\t-l,\t--list                        List available packages"
 	$echo -e "\t-b,\t--belongs file-path           List package file belongs to"
-	$echo -e "\t-D,\t--show-revdeps pkg            List reverse dependencies for a package."
+	$echo -e "\t-D,\t--show-revdeps pkg            List reverse dependencies for a package"
 	$echo -e "\t-c,\t--depcheck dynamic-binary     Check dependencies for a binary"
 	$echo -e "\t-C,\t--depcheck-system             Check dependencies for entire system"
-	$echo -e "\t-m,\t--make-bldj foo.bldj or name  Build a bldj file. If name is given pkgr will try and find it in online bldj repository."
+	$echo -e "\t-m,\t--make-bldj foo.bldj or name  Build a package (bldj file or grab it from repo)"
 	$echo -e "\t-V,\t--version-check name          Check(try) if new version is available."
 	#$echo -e "\t"
 	#$echo -e "\t-libdiff"
@@ -214,32 +214,40 @@ if [ $1 == "--version-check" ] || [ $1 == "-V" ]; then
 		
 		rm -rf /tmp/noop/verchecktmp
 		mkdir -p /tmp/noop/verchecktmp
-		pushd /tmp/noop/verchecktmp
 		
-		GetOnlineBldj
-        DLFILE=`grep "$2" /tmp/blds-list`
-        let DLFILECOUNT=`grep "$2" /tmp/blds-list | wc -l`
-        rm /tmp/blds-list
+		if ! [[ $2 =~ .*\.bldj ]];
+		then
+			pushd /tmp/noop/verchecktmp
+			GetOnlineBldj
+			DLFILE=`grep "$2" /tmp/blds-list`
+			let DLFILECOUNT=`grep "$2" /tmp/blds-list | wc -l`
+			rm /tmp/blds-list
 
-        if [ $DLFILECOUNT -gt 1 ]; then
-            echo ""
-            echo "Error - multiple packages found, please choose:"
-            echo ""
-            for i in ${DLFILE[@]};
-            do
-                echo $i | sed -e 's/\.bldj//g; s|.*/||g;';
-            done
-            exit 1;
-        fi
+			if [ $DLFILECOUNT -gt 1 ]; then
+				echo ""
+				echo "Error - multiple packages found, please choose:"
+				echo ""
+				for i in ${DLFILE[@]};
+				do
+					echo $i | sed -e 's/\.bldj//g; s|.*/||g;';
+				done
+				exit 1;
+			fi
 
-        if [ $DLFILECOUNT -eq 0 ]; then
-            echo "No instances of $2 found."
-            exit 1;
-        fi
+			if [ $DLFILECOUNT -eq 0 ]; then
+				echo "No instances of $2 found."
+				exit 1;
+			fi
 
-        wget http://www.nooplinux.org/noop/blds/$DLFILE -Ofile.bldj
-		tar xf file.bldj
-		rm file.bldj
+			wget http://www.nooplinux.org/noop/blds/$DLFILE -Ofile.bldj
+			tar xf file.bldj
+			rm file.bldj
+		else
+			BLDJFILE=`pwd`/$2
+			pushd /tmp/noop/verchecktmp
+			tar xf $BLDJFILE
+		fi
+
 		BLDFILE=`ls *.bld`
 		source ./$BLDFILE
 		Detect
